version: '3.7'
services:
    laravel-db:
        image: mysql:5.7
        container_name: mysql-ipetri
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'ipetri'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_PASSWORD: "password"
        volumes:
            - ./db:/var/lib/mysql
    laravel-app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: 'laravelapp'
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
    phpfpm:
        container_name: php-ipetri
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./:/var/www/html/
        links:
            - laravel-db